---
- name: Upgrade apt packages
  hosts: all
  become: true
  serial: 1

  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: apt upgrade
      apt:
        upgrade: yes

    - name: apt autoremove
      apt:
        autoremove: true
