---
- name: Upgrade apt packages
  hosts: all
  become: true
  serial: 1

  tasks:
    - name: Upgrade Apt Packages
      apt:
        update_cache: true
        upgrade: yes
        autoremove: true
        autoclean: true
