FROM amazoncorretto:21

EXPOSE 25565/tcp
WORKDIR /minecraft

# Install udev, and wget
RUN yum install -y udev wget && yum clean all

# Download the Minecraft server jar
RUN wget -O server.jar https://piston-data.mojang.com/v1/objects/6bce4ef400e4efaa63a13d5e6f6b500be969ef81/server.jar

# Accept the EULA
RUN echo "eula=true" > eula.txt

ENTRYPOINT cd $MC_SVR_PATH && cp /minecraft/*.* $MC_SVR_PATH && java -Xmx$MC_MEM_MAX -Xms$MC_MEM_MIN -jar ./server.jar --nogui
