FROM amazoncorretto:26

EXPOSE 25565/tcp
WORKDIR /minecraft

# Install udev, and wget
RUN yum install -y udev wget && yum clean all

# Download the Minecraft server jar
RUN wget -O server.jar https://piston-data.mojang.com/v1/objects/97ccd4c0ed3f81bbb7bfacddd1090b0c56f9bc51/server.jar

# Accept the EULA
RUN echo "eula=true" > eula.txt

ENTRYPOINT ["sh", "-c", "cd $MC_SVR_PATH && cp /minecraft/*.* $MC_SVR_PATH && java --enable-native-access=ALL-UNNAMED -Xmx$MC_MEM_MAX -Xms$MC_MEM_MIN -jar ./server.jar nogui"]
